#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'

cookbook 'apache2'
cookbook 'mysql', '= 7.1.0'
cookbook 'php', '= 2.0.0'
cookbook 'database'
cookbook 'mysql2_chef_gem', '~> 1.0.1'
cookbook 'nodejs'
