CREATE TABLE user(
	id			INT UNSIGNED	AUTO_INCREMENT,
	username	VARCHAR(10)		NOT NULL DEFAULT '',
	password	VARCHAR(20) 	NOT NULL DEFAULT '',
	email		VARCHAR(50) 	NOT NULL DEFAULT '',
	PRIMARY KEY	(id)
);

CREATE TABLE annotation(
	id			INT UNSIGNED	AUTO_INCREMENT,
	video		INT UNSIGNED	NOT NULL DEFAULT 0,
	user_id		INT UNSIGNED	NOT NULL DEFAULT 0,
	start_time	INT	UNSIGNED	NOT NULL DEFAULT 0,
	end_time	INT	UNSIGNED	NOT NULL DEFAULT 0,
	x			INT UNSIGNED	NOT NULL DEFAULT 0,
	y			INT UNSIGNED	NOT NULL DEFAULT 0,
	PRIMARY KEY (id),
	FOREIGN KEY (user_id)
		REFERENCES	user(id)
);

CREATE TABLE text(
	id				INT UNSIGNED	AUTO_INCREMENT,
	annotation_id	INT UNSIGNED	NOT NULL DEFAULT '',
	user_id			INT UNSIGNED	NOT NULL DEFAULT '',
	text			VARCHAR(100) 	NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	FOREIGN KEY (user_id)
		REFERENCES	user(id)
);

CREATE TABLE image(
	id				INT UNSIGNED	AUTO_INCREMENT,
	annotation_id	INT UNSIGNED	NOT NULL DEFAULT '',
	user_id			INT UNSIGNED	NOT NULL DEFAULT '',
	url				VARCHAR(200)	NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	FOREIGN KEY (user_id)
		REFERENCES	user(id)
);

CREATE TABLE video(
	id				INT UNSIGNED	AUTO_INCREMENT,
	annotation_id	INT UNSIGNED	NOT NULL DEFAULT '',
	user_id			INT UNSIGNED	NOT NULL DEFAULT '',
	url				VARCHAR(200)	NOT NULL DEFAULT '',
	PRIMARY KEY (id),
	FOREIGN KEY (user_id)
		REFERENCES	user(id)
);